// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	models "ygo-card-processor/models"

	mock "github.com/stretchr/testify/mock"
)

// ExtRetriever is an autogenerated mock type for the ExtRetriever type
type ExtRetriever struct {
	mock.Mock
}

// BasicCardSearch provides a mock function with given fields: serial
func (_m *ExtRetriever) BasicCardSearch(serial string) (*models.SearchResponse, error) {
	ret := _m.Called(serial)

	var r0 *models.SearchResponse
	if rf, ok := ret.Get(0).(func(string) *models.SearchResponse); ok {
		r0 = rf(serial)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.SearchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(serial)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ExtendedCardSearch provides a mock function with given fields: productId
func (_m *ExtRetriever) ExtendedCardSearch(productId int) (*models.ExtendedSearchResponse, error) {
	ret := _m.Called(productId)

	var r0 *models.ExtendedSearchResponse
	if rf, ok := ret.Get(0).(func(int) *models.ExtendedSearchResponse); ok {
		r0 = rf(productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.ExtendedSearchResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetCardPricingInfo provides a mock function with given fields: productId
func (_m *ExtRetriever) GetCardPricingInfo(productId int) (*models.PriceResponse, error) {
	ret := _m.Called(productId)

	var r0 *models.PriceResponse
	if rf, ok := ret.Get(0).(func(int) *models.PriceResponse); ok {
		r0 = rf(productId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.PriceResponse)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(int) error); ok {
		r1 = rf(productId)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// RefreshToken provides a mock function with given fields: publicKey, privateKey
func (_m *ExtRetriever) RefreshToken(publicKey string, privateKey string) error {
	ret := _m.Called(publicKey, privateKey)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(publicKey, privateKey)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
