// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import (
	multipart "mime/multipart"

	mock "github.com/stretchr/testify/mock"
)

// FileReader is an autogenerated mock type for the FileReader type
type FileReader struct {
	mock.Mock
}

// OpenAndReadFile provides a mock function with given fields: file
func (_m *FileReader) OpenAndReadFile(file multipart.File) ([]string, error) {
	ret := _m.Called(file)

	var r0 []string
	if rf, ok := ret.Get(0).(func(multipart.File) []string); ok {
		r0 = rf(file)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(multipart.File) error); ok {
		r1 = rf(file)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
